<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW0p0cUt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW0p0cUt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW0p0cUt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW0p0cUt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW0p0cUt\App_KernelDevDebugContainer([
    'container.build_hash' => 'W0p0cUt',
    'container.build_id' => '9979fa42',
    'container.build_time' => 1769688617,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW0p0cUt');
