<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCwrzR4w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCwrzR4w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCwrzR4w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCwrzR4w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCwrzR4w\App_KernelDevDebugContainer([
    'container.build_hash' => 'CwrzR4w',
    'container.build_id' => 'cffebe1d',
    'container.build_time' => 1771242493,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCwrzR4w');
