<?php

namespace ContainerEZ5YZeB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LdKWGlY.App\Controller\RegistrationController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'validator' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::register()', $container);

        if (isset($container->privates['.service_locator.LdKWGlY.App\\Controller\\RegistrationController::register()'])) {
            return $container->privates['.service_locator.LdKWGlY.App\\Controller\\RegistrationController::register()'];
        }

        return $container->privates['.service_locator.LdKWGlY.App\\Controller\\RegistrationController::register()'] = $instance;
    }
}
