<?php

namespace ContainerW0p0cUt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllercheckAuthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wNicUqG.App\Controller\SecurityController::checkAuth()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wNicUqG.App\\Controller\\SecurityController::checkAuth()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\SecurityController::checkAuth()', $container);
    }
}
